apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-docusaurus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-docusaurus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: gke-docusaurus
    spec:
      containers:
      - name: gke-docusaurus
        image: gcr.io/technifutur-tff/docusaurus:$GITHUB_SHA
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
